name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
    - name: Login to Docker registry
      run: echo $DOCKER_USERNAME && echo $DOCKER_PASSWORD && docker login w2xtfofj.gra7.container-registry.ovh.net/library/ -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: cd mc8s-bungeecord && docker build . --file Dockerfile --tag w2xtfofj.gra7.container-registry.ovh.net/library/bungeecord:latest
    - name: Push the Docker image
      run: docker push w2xtfofj.gra7.container-registry.ovh.net/library/bungeecord:latest
