name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the BungeeCord Docker image
      run: cd mc8s-bungeecord && docker build . --file Dockerfile --tag ghcr.io/mc-k8s/mc8s-bungeecord:latest
    - name: Push the BungeeCord Docker image
      run: docker push ghcr.io/mc-k8s/mc8s-bungeecord:latest

    - name: Build the GameServer Docker image
      run: cd mc8s-gameserver && docker build . --file Dockerfile --tag ghcr.io/mc-k8s/mc8s-gameserver:latest
    - name: Push the GameServer Docker image
      run: docker push ghcr.io/mc-k8s/mc8s-gameserver:latest

    - name: Build the Operator Docker image
      run: cd mc8s-operator && docker build . --file Dockerfile --tag ghcr.io/mc-k8s/mc8s-operator:latest
    - name: Push the Operator Docker image
      run: docker push ghcr.io/mc-k8s/mc8s-operator:latest